# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    facts: 'puppetlabs/facts'
    puppet_agent: 'puppetlabs/puppet_agent'
    stdlib:
      repo: 'puppetlabs/stdlib'
      ref: '8.5.0'
    inifile:
      repo: 'puppetlabs/inifile'
      ref: '6.1.0'
    archive:
      repo: 'puppet/archive'
      ref: '7.0.0'
    extlib:
      repo: 'puppet/extlib'
      ref: '7.0.0'
    systemd:
      repo: 'puppet/systemd'
      ref: '6.2.0'
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
