# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    facts: 'puppetlabs/facts'
    provision: 'puppetlabs/provision'
    puppet_agent: 'puppetlabs/puppet_agent'
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: 'v8.5.0'
    inifile:
      repo: 'https://github.com/puppetlabs/puppetlabs-inifile.git'
      ref: 'v5.4.0'
    archive:
      repo: 'https://github.com/voxpupuli/puppet-archive.git'
      ref: 'v4.5.0'
    extlib:
      repo: 'https://github.com/voxpupuli/puppet-extlib.git'
      ref: 'v6.0.0'
    systemd:
      repo: 'https://github.com/voxpupuli/puppet-systemd.git'
      ref: 'v3.10.0'
  symlinks:
    gitea: "#{source_dir}"
